import { CropMarketInfo, Market, PricePoint } from "./types";

export const REGISTERED_CROPS_MARKET: CropMarketInfo[] = [
  {
    id: "crop-paddy-01",
    name: "Paddy (Kharif Rice)",
    variety: "MTU-1010 (Swarna / Basmati)",
    icon: "🌾",
    landArea: "2.5 Acres",
    expectedYieldQtl: 120,
    defaultQuantityQtl: 100,
    harvestWindow: "13 Dec – 18 Dec 2026",
    msp: 2300,
    category: "Cereal Grain",
  },
  {
    id: "crop-mustard-02",
    name: "Mustard (Rabi Oilseed)",
    variety: "Pusa Mustard-30",
    icon: "🌻",
    landArea: "1.8 Acres",
    expectedYieldQtl: 32,
    defaultQuantityQtl: 30,
    harvestWindow: "10 Feb – 16 Feb 2027",
    msp: 5700,
    category: "Oilseed",
  },
  {
    id: "crop-wheat-03",
    name: "Wheat (Rabi Grain)",
    variety: "HD-2967 Sharbati",
    icon: "🌾",
    landArea: "3.0 Acres",
    expectedYieldQtl: 126,
    defaultQuantityQtl: 100,
    harvestWindow: "25 Mar – 30 Mar 2027",
    msp: 2400,
    category: "Cereal Grain",
  },
  {
    id: "crop-groundnut-04",
    name: "Groundnut (Peanut)",
    variety: "Kadiri-6 (High Oil)",
    icon: "🥜",
    landArea: "1.5 Acres",
    expectedYieldQtl: 28,
    defaultQuantityQtl: 25,
    harvestWindow: "20 Jan – 28 Jan 2027",
    msp: 6780,
    category: "Legume & Oilseed",
  },
  {
    id: "crop-tomato-05",
    name: "Tomato (Hybrid Fl)",
    variety: "Arka Rakshak (High Yield)",
    icon: "🍅",
    landArea: "1.0 Acre",
    expectedYieldQtl: 180,
    defaultQuantityQtl: 150,
    harvestWindow: "05 Dec – 20 Dec 2026",
    msp: 1850,
    category: "Vegetable Cash Crop",
  },
];

// Helper to generate realistic trend lines
const makeTrend = (base: number, volatility: number, trendSlope: number): {
  "7D": PricePoint[];
  "30D": PricePoint[];
  "3M": PricePoint[];
  "6M": PricePoint[];
} => {
  const days7: PricePoint[] = [];
  const days30: PricePoint[] = [];
  const months3: PricePoint[] = [];
  const months6: PricePoint[] = [];

  // 7 Days
  for (let i = 6; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    const dayName = d.toLocaleDateString("en-IN", { weekday: "short" });
    const p = Math.round(base - (i * trendSlope * 1.5) + (Math.sin(i) * volatility * 0.4));
    days7.push({ date: d.toISOString().slice(0, 10), price: p, label: dayName });
  }

  // 30 Days (every 3 days)
  for (let i = 30; i >= 0; i -= 3) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    const dateStr = d.toLocaleDateString("en-IN", { day: "numeric", month: "short" });
    const p = Math.round(base - (i * trendSlope) + (Math.sin(i * 0.5) * volatility));
    days30.push({ date: d.toISOString().slice(0, 10), price: p, label: dateStr });
  }

  // 3 Months (weekly)
  for (let i = 12; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i * 7);
    const dateStr = d.toLocaleDateString("en-IN", { day: "numeric", month: "short" });
    const p = Math.round(base - (i * 7 * trendSlope * 0.8) + (Math.cos(i) * volatility * 1.2));
    months3.push({ date: d.toISOString().slice(0, 10), price: p, label: dateStr });
  }

  // 6 Months (bi-weekly)
  for (let i = 12; i >= 0; i--) {
    const d = new Date();
    d.setMonth(d.getMonth() - Math.floor(i / 2));
    if (i % 2 === 1) d.setDate(15); else d.setDate(1);
    const dateStr = d.toLocaleDateString("en-IN", { month: "short", year: "2-digit" });
    const p = Math.round(base - (i * 14 * trendSlope * 0.7) + (Math.sin(i) * volatility * 1.5));
    months6.push({ date: d.toISOString().slice(0, 10), price: p, label: dateStr });
  }

  return { "7D": days7, "30D": days30, "3M": months3, "6M": months6 };
};

const COMMON_FACILITIES = [
  { name: "e-NAM Electronic Auction", available: true, icon: "⚡", description: "Direct bank transfer within 24 hours of trade." },
  { name: "Government Grading & Quality Testing", available: true, icon: "🔬", description: "Standard moisture and grain purity testing on site." },
  { name: "Weighbridge (Automated Electronic)", available: true, icon: "⚖️", description: "Zero discrepancy calibrated computerized scales." },
  { name: "Covered Storage & Warehouse", available: true, icon: "🏢", description: "Weatherproof transit godown with CCTV security." },
  { name: "Farmer Rest Shed & Canteen", available: true, icon: "☕", description: "Free overnight accommodation and clean drinking water." },
];

export const RAW_MARKETS_DATA: Record<string, Market[]> = {
  "crop-paddy-01": [
    {
      id: "mkt-bhadrak",
      name: "Bhadrak RMC Mandi",
      district: "Bhadrak",
      state: "Odisha",
      crop: "Paddy (Kharif Rice)",
      cropId: "crop-paddy-01",
      pricePerQuintal: 2410,
      yesterdayPrice: 2395,
      thirtyDayAgoPrice: 2280,
      distanceKm: 140,
      transportCostPerQuintal: 120,
      msp: 2300,
      updatedAt: "Today, 10:30 AM",
      tradingHours: "06:30 AM – 03:00 PM (Mon-Sat)",
      dailyArrivalQtl: 4200,
      contactPerson: "Er. Ramesh Chandra Jena (Secretary)",
      contactPhone: "+91 94371 88201",
      isEnamEnabled: true,
      paymentTerms: "Direct RTGS within 24h",
      gradeAccepted: "Grade-A & Common Swarna",
      address: "NH-16 By-pass, Charampa, Bhadrak, Odisha 756101",
      rating: 4.8,
      reviewCount: 312,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2410, 45, 4.3),
    },
    {
      id: "mkt-balasore",
      name: "Balasore Regulated Market",
      district: "Balasore",
      state: "Odisha",
      crop: "Paddy (Kharif Rice)",
      cropId: "crop-paddy-01",
      pricePerQuintal: 2350,
      yesterdayPrice: 2360,
      thirtyDayAgoPrice: 2310,
      distanceKm: 100,
      transportCostPerQuintal: 140,
      msp: 2300,
      updatedAt: "Today, 09:45 AM",
      tradingHours: "07:00 AM – 04:00 PM (Daily)",
      dailyArrivalQtl: 3100,
      contactPerson: "Sri Alok Mohanty (Market Incharge)",
      contactPhone: "+91 98610 44923",
      isEnamEnabled: true,
      paymentTerms: "Cheque / NEFT within 48h",
      gradeAccepted: "All FAQ Kharif varieties",
      address: "Station Road, Near Remuna Golei, Balasore, Odisha 756001",
      rating: 4.4,
      reviewCount: 245,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2350, 35, 1.3),
    },
    {
      id: "mkt-jaleswar",
      name: "Jaleswar Sub-Market Yard",
      district: "Balasore",
      state: "Odisha",
      crop: "Paddy (Kharif Rice)",
      cropId: "crop-paddy-01",
      pricePerQuintal: 2280,
      yesterdayPrice: 2270,
      thirtyDayAgoPrice: 2240,
      distanceKm: 80,
      transportCostPerQuintal: 110,
      msp: 2300,
      updatedAt: "Today, 11:15 AM",
      tradingHours: "08:00 AM – 02:00 PM (Mon-Fri)",
      dailyArrivalQtl: 1850,
      contactPerson: "Dr. Bipin Behera (Superintendent)",
      contactPhone: "+91 97782 50114",
      isEnamEnabled: false,
      paymentTerms: "Direct Bank Transfer (3 days)",
      gradeAccepted: "Paddy & Coarse Grains",
      address: "Market Complex, Jaleswar Bazaar, Odisha 756032",
      rating: 4.1,
      reviewCount: 120,
      facilities: COMMON_FACILITIES.map((f, i) => i === 0 ? { ...f, available: false } : f),
      priceHistory: makeTrend(2280, 25, 1.2),
    },
    {
      id: "mkt-baripada",
      name: "Baripada Main Mandi Yard",
      district: "Mayurbhanj",
      state: "Odisha",
      crop: "Paddy (Kharif Rice)",
      cropId: "crop-paddy-01",
      pricePerQuintal: 2200,
      yesterdayPrice: 2190,
      thirtyDayAgoPrice: 2180,
      distanceKm: 40,
      transportCostPerQuintal: 100,
      msp: 2300,
      updatedAt: "Today, 10:00 AM",
      tradingHours: "07:00 AM – 05:00 PM (All days)",
      dailyArrivalQtl: 2400,
      contactPerson: "Sri Subhash Patra (Secretary)",
      contactPhone: "+91 94380 12349",
      isEnamEnabled: true,
      paymentTerms: "Immediate Cash Voucher / UPI",
      gradeAccepted: "Local MTU, Basmati, IR-36",
      address: "Baghra Road, Deulasahi, Baripada, Odisha 757001",
      rating: 4.3,
      reviewCount: 198,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2200, 30, 0.6),
    },
    {
      id: "mkt-cuttack",
      name: "Cuttack Malgodown Terminal",
      district: "Cuttack",
      state: "Odisha",
      crop: "Paddy (Kharif Rice)",
      cropId: "crop-paddy-01",
      pricePerQuintal: 2460,
      yesterdayPrice: 2450,
      thirtyDayAgoPrice: 2320,
      distanceKm: 210,
      transportCostPerQuintal: 220,
      msp: 2300,
      updatedAt: "Today, 11:40 AM",
      tradingHours: "05:00 AM – 02:00 PM (Daily)",
      dailyArrivalQtl: 8500,
      contactPerson: "Sri Manoranjan Das (Chief Officer)",
      contactPhone: "+91 93371 99110",
      isEnamEnabled: true,
      paymentTerms: "Same day e-transfer",
      gradeAccepted: "Premium Grade-A Superfine",
      address: "Malgodown Goods Shed, Cuttack, Odisha 753003",
      rating: 4.6,
      reviewCount: 480,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2460, 50, 4.5),
    },
  ],

  "crop-mustard-02": [
    {
      id: "mkt-bhadrak-mst",
      name: "Bhadrak Oilseed Hub",
      district: "Bhadrak",
      state: "Odisha",
      crop: "Mustard (Rabi Oilseed)",
      cropId: "crop-mustard-02",
      pricePerQuintal: 6050,
      yesterdayPrice: 6020,
      thirtyDayAgoPrice: 5750,
      distanceKm: 140,
      transportCostPerQuintal: 140,
      msp: 5700,
      updatedAt: "Today, 10:30 AM",
      tradingHours: "07:00 AM – 03:00 PM",
      dailyArrivalQtl: 920,
      contactPerson: "Sri Pradeep Rout",
      contactPhone: "+91 94371 88201",
      isEnamEnabled: true,
      paymentTerms: "24h Bank Transfer",
      gradeAccepted: "Pusa Mustard, Black/Yellow",
      address: "Charampa, Bhadrak, Odisha",
      rating: 4.7,
      reviewCount: 160,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(6050, 110, 10.2),
    },
    {
      id: "mkt-baripada-mst",
      name: "Baripada Agricultural Mandi",
      district: "Mayurbhanj",
      state: "Odisha",
      crop: "Mustard (Rabi Oilseed)",
      cropId: "crop-mustard-02",
      pricePerQuintal: 5880,
      yesterdayPrice: 5850,
      thirtyDayAgoPrice: 5690,
      distanceKm: 40,
      transportCostPerQuintal: 80,
      msp: 5700,
      updatedAt: "Today, 09:30 AM",
      tradingHours: "08:00 AM – 04:00 PM",
      dailyArrivalQtl: 650,
      contactPerson: "Sri Subhash Patra",
      contactPhone: "+91 94380 12349",
      isEnamEnabled: true,
      paymentTerms: "Instant DBT",
      gradeAccepted: "Oil Content > 38%",
      address: "Baghra Road, Baripada, Odisha",
      rating: 4.5,
      reviewCount: 110,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(5880, 80, 6.1),
    },
    {
      id: "mkt-balasore-mst",
      name: "Balasore Regulated Market",
      district: "Balasore",
      state: "Odisha",
      crop: "Mustard (Rabi Oilseed)",
      cropId: "crop-mustard-02",
      pricePerQuintal: 5920,
      yesterdayPrice: 5900,
      thirtyDayAgoPrice: 5780,
      distanceKm: 100,
      transportCostPerQuintal: 115,
      msp: 5700,
      updatedAt: "Today, 10:15 AM",
      tradingHours: "07:30 AM – 03:30 PM",
      dailyArrivalQtl: 780,
      contactPerson: "Sri Alok Mohanty",
      contactPhone: "+91 98610 44923",
      isEnamEnabled: true,
      paymentTerms: "48h NEFT",
      gradeAccepted: "Standard FAQ Yellow/Brown",
      address: "Station Road, Balasore, Odisha",
      rating: 4.3,
      reviewCount: 95,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(5920, 75, 4.5),
    },
  ],

  "crop-wheat-03": [
    {
      id: "mkt-balasore-wht",
      name: "Balasore Grain Terminal",
      district: "Balasore",
      state: "Odisha",
      crop: "Wheat (Rabi Grain)",
      cropId: "crop-wheat-03",
      pricePerQuintal: 2540,
      yesterdayPrice: 2530,
      thirtyDayAgoPrice: 2420,
      distanceKm: 100,
      transportCostPerQuintal: 125,
      msp: 2400,
      updatedAt: "Today, 11:00 AM",
      tradingHours: "07:00 AM – 03:00 PM",
      dailyArrivalQtl: 2100,
      contactPerson: "Sri Alok Mohanty",
      contactPhone: "+91 98610 44923",
      isEnamEnabled: true,
      paymentTerms: "Same Day RTGS",
      gradeAccepted: "HD-2967, Sharbati, Lok-1",
      address: "Station Road, Balasore, Odisha",
      rating: 4.6,
      reviewCount: 140,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2540, 40, 4.0),
    },
    {
      id: "mkt-bhadrak-wht",
      name: "Bhadrak RMC Mandi",
      district: "Bhadrak",
      state: "Odisha",
      crop: "Wheat (Rabi Grain)",
      cropId: "crop-wheat-03",
      pricePerQuintal: 2580,
      yesterdayPrice: 2565,
      thirtyDayAgoPrice: 2440,
      distanceKm: 140,
      transportCostPerQuintal: 130,
      msp: 2400,
      updatedAt: "Today, 10:20 AM",
      tradingHours: "06:30 AM – 03:00 PM",
      dailyArrivalQtl: 2800,
      contactPerson: "Er. Ramesh Chandra Jena",
      contactPhone: "+91 94371 88201",
      isEnamEnabled: true,
      paymentTerms: "24h Bank Credit",
      gradeAccepted: "Mill Quality & Seed Grade",
      address: "Charampa, Bhadrak, Odisha",
      rating: 4.7,
      reviewCount: 180,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2580, 45, 4.6),
    },
    {
      id: "mkt-baripada-wht",
      name: "Baripada Main Mandi Yard",
      district: "Mayurbhanj",
      state: "Odisha",
      crop: "Wheat (Rabi Grain)",
      cropId: "crop-wheat-03",
      pricePerQuintal: 2420,
      yesterdayPrice: 2415,
      thirtyDayAgoPrice: 2390,
      distanceKm: 40,
      transportCostPerQuintal: 75,
      msp: 2400,
      updatedAt: "Today, 09:45 AM",
      tradingHours: "07:30 AM – 04:30 PM",
      dailyArrivalQtl: 1200,
      contactPerson: "Sri Subhash Patra",
      contactPhone: "+91 94380 12349",
      isEnamEnabled: true,
      paymentTerms: "Cash / UPI",
      gradeAccepted: "Local Sharbati Varieties",
      address: "Baghra Road, Baripada, Odisha",
      rating: 4.2,
      reviewCount: 88,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2420, 30, 1.0),
    },
  ],

  "crop-groundnut-04": [
    {
      id: "mkt-jaleswar-gnd",
      name: "Jaleswar Oilseed Market",
      district: "Balasore",
      state: "Odisha",
      crop: "Groundnut (Peanut)",
      cropId: "crop-groundnut-04",
      pricePerQuintal: 7100,
      yesterdayPrice: 7050,
      thirtyDayAgoPrice: 6820,
      distanceKm: 80,
      transportCostPerQuintal: 110,
      msp: 6780,
      updatedAt: "Today, 11:30 AM",
      tradingHours: "08:00 AM – 02:00 PM",
      dailyArrivalQtl: 1400,
      contactPerson: "Dr. Bipin Behera",
      contactPhone: "+91 97782 50114",
      isEnamEnabled: true,
      paymentTerms: "24h DBT",
      gradeAccepted: "Kadiri-6 Bold Pods",
      address: "Market Complex, Jaleswar, Odisha",
      rating: 4.5,
      reviewCount: 130,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(7100, 130, 9.3),
    },
    {
      id: "mkt-bhadrak-gnd",
      name: "Bhadrak RMC Mandi",
      district: "Bhadrak",
      state: "Odisha",
      crop: "Groundnut (Peanut)",
      cropId: "crop-groundnut-04",
      pricePerQuintal: 7250,
      yesterdayPrice: 7200,
      thirtyDayAgoPrice: 6890,
      distanceKm: 140,
      transportCostPerQuintal: 135,
      msp: 6780,
      updatedAt: "Today, 10:45 AM",
      tradingHours: "06:30 AM – 03:00 PM",
      dailyArrivalQtl: 1800,
      contactPerson: "Er. Ramesh Chandra Jena",
      contactPhone: "+91 94371 88201",
      isEnamEnabled: true,
      paymentTerms: "RTGS in 24h",
      gradeAccepted: "Handpicked Premium Pods",
      address: "Charampa, Bhadrak, Odisha",
      rating: 4.8,
      reviewCount: 190,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(7250, 140, 12.0),
    },
    {
      id: "mkt-baripada-gnd",
      name: "Baripada Main Mandi Yard",
      district: "Mayurbhanj",
      state: "Odisha",
      crop: "Groundnut (Peanut)",
      cropId: "crop-groundnut-04",
      pricePerQuintal: 6920,
      yesterdayPrice: 6900,
      thirtyDayAgoPrice: 6750,
      distanceKm: 40,
      transportCostPerQuintal: 70,
      msp: 6780,
      updatedAt: "Today, 09:50 AM",
      tradingHours: "07:30 AM – 04:00 PM",
      dailyArrivalQtl: 950,
      contactPerson: "Sri Subhash Patra",
      contactPhone: "+91 94380 12349",
      isEnamEnabled: true,
      paymentTerms: "Direct UPI / Cash Voucher",
      gradeAccepted: "Standard Pods",
      address: "Baghra Road, Baripada, Odisha",
      rating: 4.4,
      reviewCount: 105,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(6920, 90, 5.6),
    },
  ],

  "crop-tomato-05": [
    {
      id: "mkt-cuttack-tom",
      name: "Cuttack Chhatra Bazaar Vegetable Mandi",
      district: "Cuttack",
      state: "Odisha",
      crop: "Tomato (Hybrid Fl)",
      cropId: "crop-tomato-05",
      pricePerQuintal: 2150,
      yesterdayPrice: 2100,
      thirtyDayAgoPrice: 1780,
      distanceKm: 210,
      transportCostPerQuintal: 210,
      msp: 1850,
      updatedAt: "Today, 07:30 AM",
      tradingHours: "04:00 AM – 12:00 PM (Daily)",
      dailyArrivalQtl: 6500,
      contactPerson: "Sri Manoranjan Das",
      contactPhone: "+91 93371 99110",
      isEnamEnabled: true,
      paymentTerms: "Immediate Cash / NEFT",
      gradeAccepted: "Firm Red Grade-A",
      address: "Chhatra Bazaar Terminal, Cuttack, Odisha",
      rating: 4.7,
      reviewCount: 350,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2150, 120, 12.3),
    },
    {
      id: "mkt-baripada-tom",
      name: "Baripada Daily Sabzi Mandi",
      district: "Mayurbhanj",
      state: "Odisha",
      crop: "Tomato (Hybrid Fl)",
      cropId: "crop-tomato-05",
      pricePerQuintal: 1940,
      yesterdayPrice: 1910,
      thirtyDayAgoPrice: 1820,
      distanceKm: 40,
      transportCostPerQuintal: 65,
      msp: 1850,
      updatedAt: "Today, 07:00 AM",
      tradingHours: "05:00 AM – 01:00 PM (Daily)",
      dailyArrivalQtl: 2100,
      contactPerson: "Sri Subhash Patra",
      contactPhone: "+91 94380 12349",
      isEnamEnabled: false,
      paymentTerms: "Immediate Cash",
      gradeAccepted: "All fresh table tomatoes",
      address: "Daily Market Yard, Baripada, Odisha",
      rating: 4.3,
      reviewCount: 160,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(1940, 70, 4.0),
    },
    {
      id: "mkt-balasore-tom",
      name: "Balasore Wholesale Veg Yard",
      district: "Balasore",
      state: "Odisha",
      crop: "Tomato (Hybrid Fl)",
      cropId: "crop-tomato-05",
      pricePerQuintal: 2020,
      yesterdayPrice: 2000,
      thirtyDayAgoPrice: 1840,
      distanceKm: 100,
      transportCostPerQuintal: 110,
      msp: 1850,
      updatedAt: "Today, 08:15 AM",
      tradingHours: "05:30 AM – 02:00 PM",
      dailyArrivalQtl: 3400,
      contactPerson: "Sri Alok Mohanty",
      contactPhone: "+91 98610 44923",
      isEnamEnabled: true,
      paymentTerms: "Same day UPI transfer",
      gradeAccepted: "Grade A/B",
      address: "Station Road Yard, Balasore, Odisha",
      rating: 4.5,
      reviewCount: 210,
      facilities: COMMON_FACILITIES,
      priceHistory: makeTrend(2020, 85, 6.0),
    },
  ],
};

export const TRANSPORT_MODES = [
  {
    type: "Tata Ace / Mini Truck (Pick-up)",
    capacityQtl: "15 - 25 Qtl",
    costPerKm: "₹18 - ₹22 / km",
    bestFor: "Small harvests & quick delivery",
    icon: "🛻",
    availability: "High (Within 1 hour)",
  },
  {
    type: "Tractor Trolley (Dual Axle)",
    capacityQtl: "40 - 70 Qtl",
    costPerKm: "₹28 - ₹34 / km",
    bestFor: "Medium farm harvests up to 80 km",
    icon: "🚜",
    availability: "Immediate via Local Cooperative",
  },
  {
    type: "6-Wheeler Medium Truck (Canter)",
    capacityQtl: "90 - 150 Qtl",
    costPerKm: "₹38 - ₹45 / km",
    bestFor: "Bulk harvest dispatch to regional hub mandis",
    icon: "🚚",
    availability: "Available via Smart Crop Logistics",
  },
];
